export var URL_TO_LOGIN={
    url:'http://127.0.0.1:8090',
    signin:'/api/auth/signin',
    signup:'/api/auth/signup',
    signupwork:'/api/auth/signupwork',
    updCre:'/api/entidad/cliente',
    updCreEmp:'/api/entidad/empleado',
    reqPass:'/api/auth/requestpass',//luego debe ir el nombre de usuario
    chgPasw:'/api/auth/changepassword/',
    regVehiculo:'/api/vehiculo/vehiculo',
    regCategoria:'/api/categoria/categoria',
    regProducto:'/api/producto/producto',
    updateProducto:'/api/producto/producto',
    regServicio:'/api/servicio/servicio',
    updateServicio:'/api/servicio/servicio',
    getCategoria:'/api/categoria/categorias?',
    getCategoriaId:'/api/categoria/categorias',
    getServicioId:'/api/servicio/servicios',
    getProductos:'/api/producto/allproducto?',
    getVeiculosPorId:'/api/vehiculo',
    getClientesPag:'/api/entidad/allclientes',
    getAllCategorias:'/api/categoria/categorias',
    getAllServicios:'/api/servicio/servicios',
    getAllProductoById:'/api/producto',
    reservation:'/api/reserva/reserva',
    getSerivicios:'/api/servicio/servicios?',
    getReservaPorId:'/api/reserva',
}
